### ISSUE TITLE
nested json not work

### ISSUE THREAD

**Issue by arthurtalkgoal** [jeresig/i18n-node-2#50] opened 2015-03-26 10:11 UTC
I cannot use the following notation to access ***__('contact.name')***
```
{
  "contact": {
      "name": "姓名"
  }

}

```

In i18n, this is allowed:

https://github.com/mashpie/i18n-node#object-notation

```
Instead of calling __("Hello") you might call __("greeting.formal") to retrieve a formal greeting from a translation document like this one:

"greeting": {
    "formal": "Hello",
    "informal": "Hi",
    "placeholder": {
        "formal": "Hello %s",
        "informal": "Hi %s"
    }
}
```

**Comment by blowsie** [comment] 2015-05-07 08:07
Duplicate of #44

**Comment by gjuchault** [comment] 2015-06-23 22:11
Works !

**Closed by gjuchault** 2015-06-23 22:11 UTC

**Comment by cbaigorri** [comment] 2015-07-07 21:45
I am unable to get this working after [this commit](https://github.com/jeresig/i18n-node-2/commit/47420e8a157f2ff98e16a79d51219ae964a279a2)

Lines 295 to 303 end up creating properties if they do not exist:
```
if (!this.locales[locale][singular]) {
	this.locales[locale][singular] = plural ?
		{ one: singular, other: plural } :
			singular;

	if (this.devMode) {
		this.writeFile(locale);
	}
}
```

Then in the dotNotation method they always pass the `obj.hasOwnProperty(str)` check.

Can you show an example of this working?

**Comment by gjuchault** [comment] 2015-07-07 21:52
Pense post an example of a buggy code. hasOwnProperty was there just to
avoid dot notation if not needed..

**Comment by gjuchault** [comment] 2015-07-08 17:12
Okay I did see where was the problem.
I solved it in the last commit.
