### ISSUE TITLE
fallback to default locale

### ISSUE THREAD

**Issue by torvalde** [jeresig/i18n-node-2#42] opened 2014-09-26 13:35 UTC
When in production mode and a key does not exist in the current language, the key is displayed. We have some keys that are generated so we want to avoid showing them to the customer even if a translation in the current language is not available, instead we would like to show the translation in the default language.

Would it be ok to first check the translation in the default locale before returning the key?

Something like:

        if (!this.locales[locale][singular]) {
            if (this.devMode) {
                this.locales[locale][singular] = plural ? { one: singular, other: plural } : singular;
                this.writeFile(locale);
            } else {
                locale = this.defaultLocale;
            }
        }

**Comment by gjuchault** [comment] 2015-06-23 22:12
Duplicate of https://github.com/jeresig/i18n-node-2/pull/29

**Closed by gjuchault** 2015-06-23 22:12 UTC
